import Head from 'next/head';
import NavBar from '../../components/navbar/navbar';
import Footer from '../../components/footer/footer';

export default function BaseLayout(props) {
    return (
        <div>
            <Head>
                <title>{props.page.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
            </Head>
            <NavBar {...props.siteConfig} />
            {props.children}
            <Footer {...props.siteConfig} />
        </div>
    );
}
