// ⚠️ This file is autogenerated by 'scripts/generate-storybook-dynamic.js'
// To update this file, change 'src/components-manifest.json' and re-run 'npm run build'

import { components, layouts } from '../src';

const dynamicComponents = {
    ContactSection: components.ContactSection,
    CtaSection: components.CtaSection,
    HeroSection: components.HeroSection,
    ImageBlock: components.ImageBlock,
    PostsSection: components.PostsSection,
    TestimonialsSection: components.TestimonialsSection,
    VideoBlock: components.VideoBlock,
    advanced: layouts.AdvancedLayout,
    post: layouts.PostLayout
};

export default dynamicComponents;
