// ⚠️ This file is autogenerated by build-component-maps.js
// To update this file, change src/components-manifest.json and re-run build-component-maps.js

import { components, layouts } from '../src';

const dynamicComponents = {
    ContactSection: components.ContactSection,
    CtaSection: components.CtaSection,
    HeroSection: components.HeroSection,
    ImageBlock: components.ImageBlock,
    PostsSection: components.PostsSection,
    TestimonialsSection: components.TestimonialsSection,
    VideoBlock: components.VideoBlock,
    advanced: layouts.AdvancedLayout,
    normal: base.NormalBase,
    blank: base.BlankBase
};

export default dynamicComponents;
