// ⚠️ This file is autogenerated by 'scripts/generate-storybook-dynamic.js'
// To update this file, change 'src/components-manifest.json' and re-run 'npm run build'

import { components, layouts } from '../src';

const dynamicComponents = {
    CheckboxFormControl: components.CheckboxFormControl,
    ContactSection: components.ContactSection,
    ContentSection: components.ContentSection,
    CtaSection: components.CtaSection,
    EmailFormControl: components.EmailFormControl,
    FeaturedPeopleSection: components.FeaturedPeopleSection,
    FeaturedPostsSection: components.FeaturedPostsSection,
    FormBlock: components.FormBlock,
    HeroSection: components.HeroSection,
    ImageBlock: components.ImageBlock,
    SelectFormControl: components.SelectFormControl,
    TestimonialsSection: components.TestimonialsSection,
    TextFormControl: components.TextFormControl,
    TextareaFormControl: components.TextareaFormControl,
    VideoBlock: components.VideoBlock,
    FeatureSection: components.FeatureSection,
    AdvancedLayout: layouts.AdvancedLayout,
    PostLayout: layouts.PostLayout
};

export default dynamicComponents;
