// ⚠️ This file is automatically generated when next.js starts ⚠️
// To override and customize components please use the _app.js file

import dynamic from 'next/dynamic';

const components = {
  advanced: dynamic(() => import('@stackbit/components/layouts/advanced')),
  contact_section: dynamic(() => import('@stackbit/components/components/contact-section')),
  cta_section: dynamic(() => import('@stackbit/components/components/cta-section')),
  hero_section: dynamic(() => import('@stackbit/components/components/hero-section')),
  testimonials_section: dynamic(() => import('@stackbit/components/components/testimonials-section')),
  posts_section: dynamic(() => import('@stackbit/components/components/posts-section')),
  video_block: dynamic(() => import('@stackbit/components/components/video-block')),
  image_block: dynamic(() => import('@stackbit/components/components/image-block'))
};

export default components;
