type: object
label: Action
fields:
  - type: string
    name: label
    label: Label
  - type: string
    name: url
    label: URL
    default: '#'
  - type: string
    name: altText
    label: Title
  - type: enum
    name: type
    label: Type
    options:
      - label: Link
        value: link
      - label: Primary button
        value: primary-button
      - label: Secondary button
        value: secondary-button
    default: link
  - type: enum
    name: icon
    label: Icon
    options:
      - arrowRight
      - cart
      - facebook
      - github
      - instagram
      - linkedin
      - twitter
